name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
      - uses: actions/checkout@v2
      - name: Configure
        run: qmake
      - name: Compile (other OS)
        run: make
  build-win:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.9.0
      - uses: actions/checkout@v2
      - name: Build
        run: |
          Install-Module -Name Pscx -Force -AllowClobber
          Invoke-BatchFile "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake
          nmake
